version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=fymorpgadmin
      - POSTGRES_PASSWORD=fymorpgpassword#
      - POSTGRES_DB=root      
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "fymor6@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "231199F#"
    ports:
      - "54321:80"
    depends_on:
      - postgres